version: '3.4'

services:
  financetracker.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8000
      - ASPNETCORE_HTTPS_PORTS=8001
    ports:
      - "8000"
      - "8001"
    volumes:
      - /var/https:/root/.aspnet/https:ro
