version: "3.4"

networks:
  financetracker:

services:
  financetracker.api:
    container_name: finance-tracker-api
    image: ${DOCKER_REGISTRY-}financetracker.api
    build:
      context: .
      dockerfile: FinanceTracker.Api/Dockerfile
    ports:
      - 8000:8000
      - 8001:8001