version: "3.4"

networks:
  financetracker:

services:
  financetracker.db:
    container_name: financetracker-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd.
  
  financetracker.api:
    container_name: finance-tracker-api
    image: ${DOCKER_REGISTRY-}financetracker.api
    build:
      context: .
      dockerfile: FinanceTracker.Api/Dockerfile
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - financetracker.db