# fly.toml app configuration file generated for financetracker on 2024-07-31T18:15:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'financetracker'

[build]
  dockerfile = 'FinanceTracker.Api/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
